language: r
sudo: required

r_github_packages:
 - data-camp/datacampAPI
 - hadley/testthat

after_failure:
 - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
