language: R
sudo: false
cache: packages
r_check_args: --as-cran

install:
  - R -e 'install.packages(c("devtools", "dplyr", "ggvis", "ggplot2", "car", "RColorBrewer", "rpart", "pkgdown"))'
  - R -e 'devtools::install_github(c("datacamp/r-completion", "datacamp/r-backend", "datacamp/testwhat.base"))'
  - R -e 'devtools::install(".")'

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master
